name: 'adain'

vocoder:
    name: melgan

n_speaker: 80
n_data_per_speaker: 200
seg_len: 128
   
model:
    speaker:
        c_in: 80
        c_h: 128
        c_out: 128
        kernel_size: 5
        bank_size: 8
        bank_scale: 1
        c_bank: 128
        n_conv_blocks: 6
        n_dense_blocks: 6
        subsample: [1, 2, 1, 2, 1, 2]
        act: 'relu'
        dropout_rate: 0
    content:
        c_in: 80
        c_h: 128
        c_out: 128
        kernel_size: 5
        bank_size: 8
        bank_scale: 1
        c_bank: 128
        n_conv_blocks: 6
        subsample: [1, 2, 1, 2, 1, 2]
        act: 'relu'
        dropout_rate: 0
    decoder:
        c_in: 128
        c_cond: 128
        c_h: 128
        c_out: 80
        kernel_size: 5
        n_conv_blocks: 6
        upsample: [2, 1, 2, 1, 2, 1]
        act: 'relu'
        sn: False
        dropout_rate: 0
    classifier:
        c_in: 128
        c_h: 128
        c_out: 80

loss:
    lambda_rec: 10
    lambda_kl: 1
    annealing_steps: 20000

grad_norm: 5

optimizer:
    name: Adam
    lr: 0.0005
    betas:
        - 0.9
        - 0.999
    amsgrad: True
    weight_decay: 0.0001

classifier:
    model:
        c_in: 128
        c_h: 128
        c_out: 80
    optimizer:
        name: Adam
        lr: 0.0005
        betas:
            - 0.9
            - 0.999

