name: vqvc_plus-vctk-v1

vocoder:
    name: melgan

n_speaker: 80
n_data_per_speaker: 200
seg_len: 128


model:
    in_channel: 80
    channel: 512
    n_embed: 128


loss_params:
    lambda_latent: 0.1

optimizer:
    name: Adam
    lr: 1.0E-3

grad_norm: 3


# Speaker classfier on content embedding

classifier:
    model:
        c_in: 40
        c_h: 128
        c_out: 80
        
    optimizer:
        name: Adam
        lr: 0.0005
        betas:
            - 0.9
            - 0.999

