name: vqvc+

vocoder:
    name: melgan

dataset:
    name: mel_trim
    root_dir: /home/anly/Documents/coolproject/PyTorch-Voice-Conversion/data/feature/vctk
    seg_len: 128
    max_data: null
    n_speaker: 80
    n_data_per_speaker: 200

model:
    batch_size: 32
    model:
        in_channel: 80
        channel: 512
        n_embed: 128
    loss:
        lambda_latent: 0.1
    optimizer:
        name: Adam
        lr: 1.0E-3
    classifier:
        model:
            c_in: 40
            c_h: 128
            c_out: 80
        optimizer:
            name: Adam
            lr: 0.0005
            betas:
                - 0.9
                - 0.999

trainer:
    gpus: 1
    max_steps: 100000
    log_every_n_steps: 1000
    gradient_clip_val: 3
    save_every_n_train_steps: 10000
